@isTest
public class CreateProductComponent_ControllerTest {
    @isTest static void testNameAllClassdata() {
        CreateProductComponent_Controller.getRelatedFields('Name');
        CreateProductComponent_Controller.nameFormat('Name');
        CreateProductComponent_Controller.testMethodClass1();
        ConvertCurrencyToWords.convert_nnn(22);
        ConvertCurrencyToWords.english_number(22);
        ConvertCurrencyToWords.testMethodClass();
        CustomCloseAuraHelper.testMethodClass212();
    }
}